import * as T from 'three';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {LEVELS} from './levels';
import {ArcadeAudio} from './audio';
const $=(id:string)=>document.getElementById(id)!;
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.NeutralToneMapping;renderer.toneMappingExposure=1.05;$('world').appendChild(renderer.domElement);
const scene=new T.Scene(),camera=new T.PerspectiveCamera(76,innerWidth/innerHeight,.1,240);camera.rotation.order='YXZ';scene.add(camera);
const hemi=new T.HemisphereLight(0xfff7e6,0x577ba1,2.5),sun=new T.DirectionalLight(0xfff1d7,2.6);sun.position.set(-25,45,20);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-52,right:52,top:52,bottom:-52,far:140});sun.shadow.bias=-.001;scene.add(hemi,sun);
let world=new T.Group();scene.add(world);const mats=new Map<number,T.MeshStandardMaterial>();const mat=(c:number)=>{if(!mats.has(c))mats.set(c,new T.MeshStandardMaterial({color:c,roughness:.55}));return mats.get(c)!;};
function mesh(g:T.BufferGeometry,c:number,x=0,y=0,z=0,parent:T.Object3D=world){const m=new T.Mesh(g,mat(c));m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;parent.add(m);return m;}
const box=(w:number,h:number,d:number,c:number,x:number,y:number,z:number,p:T.Object3D=world)=>mesh(new RoundedBoxGeometry(w,h,d,1,.08),c,x,y,z,p);
const ball=(r:number,c:number,x:number,y:number,z:number,p:T.Object3D=world)=>mesh(new T.SphereGeometry(r,16,10),c,x,y,z,p);
const cyl=(r:number,h:number,c:number,x:number,y:number,z:number,p:T.Object3D=world)=>mesh(new T.CylinderGeometry(r,r,h,16),c,x,y,z,p);
function dispose(o:T.Object3D){o.removeFromParent();o.traverse((m:any)=>{m.geometry?.dispose();if(m instanceof T.Sprite)m.material.map?.dispose();if(m.material&&!Array.isArray(m.material)&&!Array.from(mats.values()).includes(m.material))m.material.dispose();});}
type EnemyKind="toy"|"dinosaur"|"ninja"|"alien";
const ROSTERS:EnemyKind[][]=[["dinosaur"],["dinosaur","toy"],["dinosaur"],["ninja"],["ninja","dinosaur"],["ninja","toy"],["alien","dinosaur"],["dinosaur","ninja"],["alien"],["dinosaur","ninja","alien"]];
const enemyKind=(index:number):EnemyKind=>ROSTERS[level][index%ROSTERS[level].length];
type Enemy={kind:EnemyKind,id:number,obj:T.Group,x:number,z:number,hp:number,max:number,boss:boolean,phase:number,cool:number,wind:number,legs:T.Group[],arms:T.Group[],radius:number};
type Cover={x:number,z:number,w:number,d:number,h:number};type Particle={obj:T.Object3D,life:number,total:number,v:T.Vector3,growth:number};
let building=false,buildType=0,buildRotation=0,buildCount=0;const ghost=new T.Group();scene.add(ghost);
let moveX=0,moveY=0,movePointer:number|null=null,lookPointer:number|null=null;
let bolts:{obj:T.Group,v:T.Vector3,life:number,damage:number,spin:boolean}[]=[];
let covers:Cover[]=[],enemies:Enemy[]=[],fx:Particle[]=[],shots:{obj:T.Mesh,v:T.Vector3,life:number,damage:number}[]=[],grenades:{obj:T.Group,v:T.Vector3,fuse:number}[]=[],pickups:T.Mesh[]=[],portal:T.Group|null=null,weapon=0,ammo=[24,6,32,3],reload=0,fireCd=0,hp=100,score=0,level=0,wave=0,kills=0,mode='menu',clock=0,vy=0,jumps=0,yaw=0,pitch=0,mouse=false,lock=false,drag=false,lastX=0,lastY=0,audio:ArcadeAudio|null=null,music=true,muted=false,unlocked=1,save:any={},sprint=false;
const pos=new T.Vector3(0,1.7,12),keys=new Set<string>(),gun=new T.Group();camera.add(gun);const weapons=[{name:'POP RIFLE',damage:25,rate:.20,cap:24,color:0x9e87e7},{name:'BOOM SHOTGUN',damage:62,rate:.75,cap:6,color:0xffbc67},{name:'SPLAT GUN',damage:20,rate:.13,cap:32,color:0x52dcb8},{name:'POP GRENADES',damage:85,rate:1,cap:3,color:0xf17db6},{name:'CROSSBOW',damage:95,rate:.85,cap:5,color:0xffca78},{name:'SWORD',damage:80,rate:.5,cap:Infinity,color:0xaee8ff},{name:'THROWING STARS',damage:40,rate:.32,cap:12,color:0xe2a5fa},{name:'MACHINE GUN',damage:14,rate:.075,cap:60,color:0x90bcf0}];
try{save=JSON.parse(localStorage.getItem('popshotSoloSave')||'{}');unlocked=Math.max(1,Math.min(10,Number(save.unlocked)||1));}catch{}
function saveProgress(){try{localStorage.setItem('popshotSoloSave',JSON.stringify(save));}catch{}}
const levelMusic=new Audio('music/pixel-blast.mp3');levelMusic.loop=true;levelMusic.preload='none';levelMusic.volume=.12;
function playLevelMusic(restart=false){if(restart)levelMusic.currentTime=0;levelMusic.muted=muted;if(mode==='play'&&!muted)levelMusic.play().catch(()=>{});}
function pauseLevelMusic(){levelMusic.pause();}
function sound(s:any){try{if(!audio){const ac=new AudioContext();audio=new ArcadeAudio(ac);}if(audio.context.state==='suspended')audio.context.resume().catch(()=>{});audio.muted=muted;audio.musicEnabled=false;audio.update();audio.play(s);}catch{}}
function particles(at:T.Vector3,color:number,count=12,speed=5){for(let i=0;i<count;i++){const p=ball(.08+Math.random()*.08,color,at.x,at.y,at.z,scene);fx.push({obj:p,life:.6+Math.random()*.4,total:1,v:new T.Vector3((Math.random()-.5)*speed,Math.random()*speed,(Math.random()-.5)*speed),growth:0});}}
function confetti(at:T.Vector3){[0xff6bb6,0xffdc65,0x76efda,0xab8aff].forEach(c=>particles(at,c,12,12));const ring=new T.Mesh(new T.TorusGeometry(.7,.07,8,48),new T.MeshBasicMaterial({color:0xffeab0,transparent:true,opacity:.8}));ring.rotation.x=Math.PI/2;ring.position.copy(at);scene.add(ring);fx.push({obj:ring,life:.6,total:.6,v:new T.Vector3(),growth:9});}
function label(text:string){const c=document.createElement('canvas');c.width=512;c.height=96;const ctx=c.getContext('2d')!;ctx.font='900 52px Arial';ctx.textAlign='center';ctx.fillStyle='#ffffff';ctx.strokeStyle='#364965';ctx.lineWidth=8;ctx.strokeText(text,256,65);ctx.fillText(text,256,65);const texture=new T.CanvasTexture(c);texture.colorSpace=T.SRGBColorSpace;const sprite=new T.Sprite(new T.SpriteMaterial({map:texture}));sprite.scale.set(6,1.1,1);return sprite;}
function blocked(x:number,z:number,y=0){return Math.abs(x)>LEVELS[level].half-1||Math.abs(z)>LEVELS[level].half-1||covers.some(c=>Math.abs(x-c.x)<c.w/2+.35&&Math.abs(z-c.z)<c.d/2+.35&&y<c.h-.25);}
function floor(x:number,z:number){let h=0;for(const c of covers)if(Math.abs(x-c.x)<c.w/2&&Math.abs(z-c.z)<c.d/2)h=Math.max(h,c.h);return h;}
function clear(a:T.Vector3,b:T.Vector3){const n=Math.ceil(a.distanceTo(b)*6);for(let i=1;i<n;i++){const p=a.clone().lerp(b,i/n);if(covers.some(c=>Math.abs(p.x-c.x)<c.w/2&&Math.abs(p.z-c.z)<c.d/2&&p.y<c.h))return false;}return true;}
function rng(seed:number){return()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};}
function buildMap(n:number){dispose(world);world=new T.Group();scene.add(world);covers=[];const l=LEVELS[n],rand=rng(904+n*771),h=l.half;scene.background=new T.Color(l.sky);scene.fog=new T.Fog(l.sky,h*1.4,h*4);box(h*2+4,1.5,h*2+4,l.ground,0,-.75,0);for(let i=0;i<3;i++)box(h*2+4-i*1.7,.65,h*2+4-i*1.7,0xc6ad92,0,-1.8-i*.65,0);
 const water=mesh(new T.PlaneGeometry(400,400),l.water,0,-4.2,0);water.rotation.x=-Math.PI/2;water.castShadow=false;
 const path=0xf5e9c9;box(h*1.65,.03,4,path,0,.015,0);box(4,.03,h*1.65,path,0,.02,0);
 // Clear central arena and open radial lanes; each theme has a different layout.
 for(let i=0;i<8+n;i++){const a=i/(8+n)*Math.PI*2+n*.37,r=8+(i%3)*((h-12)/3),x=Math.cos(a)*r,z=Math.sin(a)*r,w=2.2+rand()*1.3,height=1.2+rand()*1.6;if(Math.abs(x)<w/2+1.2&&z+w/2>-2&&z-w/2<6)continue;covers.push({x,z,w,d:w,h:height});box(w,height,w,i%2?l.accent:0xf8ecd9,x,height/2,z);box(w+.1,.12,w+.1,0xffffff,x,height+.04,z);for(let j=0;j<2;j++)box(.45,.55,.08,0x59778c,x+(j-.5)*.9,height*.65,z-w/2-.06);}
 for(let i=0;i<24;i++){const a=i/24*Math.PI*2,x=Math.cos(a)*(h+.1),z=Math.sin(a)*(h+.1),c=[0x70b896,0x85c4a3,0x52a993][i%3];
 if(l.theme==='mushroom'||l.theme==='candy'){cyl(.4,2.4,0xfff0d7,x,1.2,z);const cap=ball(1.6,l.theme==='candy'?l.accent:0xf98e8e,x,3,z);cap.scale.y=.55;for(let j=0;j<3;j++)ball(.22,0xfff5df,x+Math.cos(j*2)*.8,3.5,z+Math.sin(j*2)*.8);}
 else if(['crystal','space','volcano'].includes(l.theme)){for(let j=0;j<3;j++){const cr=mesh(new T.ConeGeometry(.7,3+j*.6,5),j%2?l.accent:0xc8e9f2,x+j*.6-.6,1.4+j*.3,z);cr.rotation.z=(j-1)*.25;}}
 else if(l.theme==='coral'){cyl(.24,3,l.accent,x,1.5,z);for(let j=0;j<3;j++){const branch=cyl(.16,2,l.accent,x+Math.cos(j*2)*.6,2.3,z+Math.sin(j*2)*.6);branch.rotation.z=(j-1)*.6;ball(.45,0xffdccb,x+Math.cos(j*2),3.2,z+Math.sin(j*2));}}
 else{cyl(.32,3,0x9e816e,x,1.4,z);for(let j=0;j<3;j++)ball(1.5-j*.2,c,x+Math.cos(j*2)*.6,3.2+j*.5,z+Math.sin(j*2)*.6);}}
 for(let i=0;i<90;i++){const x=(rand()-.5)*h*2,z=(rand()-.5)*h*2;if(Math.abs(x)<3||Math.abs(z)<3||blocked(x,z))continue;const flower=mesh(new T.ConeGeometry(.12,.5,5),i%4?0x66977b:l.accent,x,.22,z);flower.rotation.z=.15;}
 for(let i=0;i<9;i++){const cloud=new T.Group();for(let j=0;j<3;j++)ball(2.4,0xffffff,j*2.3,j===1?.5:0,0,cloud);cloud.position.set(Math.cos(i)*h*1.8,14+i%3*4,Math.sin(i)*h*1.8);world.add(cloud);}
 const landmark=new T.Group();landmark.position.set(0,0,-h+4);world.add(landmark);if(['carnival','rainbow','candy'].includes(l.theme)){for(let i=0;i<5;i++){const arch=new T.Mesh(new T.TorusGeometry(4+i*.25,.18,10,40,Math.PI),mat([0xff83b2,0xffd880,0x87dbc6,0x85bceb,0xb4a3e7][i]));arch.position.y=2;arch.position.z=i*.25;landmark.add(arch);}cyl(.3,3.5,l.accent,-4,1.75,0,landmark);cyl(.3,3.5,l.accent,4,1.75,0,landmark);}else{for(const x of [-4,4]){cyl(.8,5.5,l.accent,x,2.75,0,landmark);ball(1,0xffefcf,x,5.8,0,landmark);}box(10,.8,1.5,l.accent,0,5,0,landmark);}
 const title=label(l.name.toUpperCase());title.position.set(0,8,-h+4);world.add(title);
 if(l.theme==='space'||l.theme==='rainbow'){for(let i=0;i<3;i++){const planet=ball(3+i,l.accent,(i-1)*h,20+i*4,-h*1.8);const ring=mesh(new T.TorusGeometry(4.5+i,.18,8,48),0xffedc6,0,0,0,planet);ring.rotation.x=1.1;}}
}
function creature(kind:EnemyKind,index:number){const g=new T.Group(),legs:T.Group[]=[],arms:T.Group[]=[];const color=kind==='dinosaur'?[0x69cf91,0x7bbbe7,0xf5b77d][index%3]:kind==='alien'?[0x8ddeca,0xbc99f1,0x8cbcea][index%3]:[0x485578,0x695488,0x456b6c][index%3];
 box(.78,.78,.55,color,0,1.05,0,g);box(.46,.55,.06,kind==='dinosaur'?0xffe5a5:kind==='alien'?0xd9f3ef:0x28394d,0,1.04,-.3,g);
 for(const side of [-1,1]){const leg=new T.Group();leg.position.set(side*.23,.67,0);box(.28,.48,.3,color,0,-.24,0,leg);box(.34,.16,kind==='dinosaur'?.55:.4,kind==='ninja'?0x24334d:color,0,-.5,-.1,leg);g.add(leg);legs.push(leg);const arm=new T.Group();arm.position.set(side*.51,1.4,0);box(.22,.43,.25,color,0,-.22,0,arm);box(.25,.16,.25,color,0,-.47,-.06,arm);g.add(arm);arms.push(arm);}
 if(kind==='dinosaur'){box(.73,.58,.7,color,0,1.78,-.08,g);box(.67,.26,.5,color,0,1.64,-.5,g);box(.61,.045,.32,0xfff3ce,0,1.54,-.61,g);for(const side of [-1,1]){ball(.105,0xffffff,side*.37,1.91,-.25,g);ball(.06,0x30435b,side*.41,1.91,-.28,g);box(.07,.06,.04,0x3f755d,side*.2,1.75,-.76,g);}for(let i=0;i<4;i++){box(.4-i*.07,.26-i*.035,.36,color,0,.85-i*.08,.44+i*.27,g);const spike=mesh(new T.ConeGeometry(.13,.3,4),0xffcd78,0,1.54-i*.18,.23+i*.23,g);spike.rotation.x=.4;}}
 if(kind==='ninja'){cyl(.34,.55,color,0,1.8,0,g);box(.52,.16,.05,0xffdeaf,0,1.86,-.32,g);for(const side of [-1,1])box(.06,.045,.025,0x263c53,side*.13,1.86,-.36,g);cyl(.35,.09,0xf295ae,0,2.02,0,g);box(.18,.08,.62,0xf295ae,.22,1.99,.35,g);box(.84,.12,.6,0xf295ae,0,.88,0,g);const sword=box(.09,.95,.08,0xc6e9ef,.25,1.24,.36,g);sword.rotation.z=-.5;box(.34,.06,.1,0xffd37a,.4,.98,.4,g);}
 if(kind==='alien'){const head=ball(.44,color,0,1.84,0,g);head.scale.set(1.15,1,.8);for(const side of [-1,1]){const eye=ball(.14,0x293c61,side*.19,1.89,-.3,g);eye.scale.y=1.3;ball(.04,0xffffff,side*.19-.025,1.94,-.42,g);cyl(.035,.35,color,side*.22,2.31,0,g);ball(.085,0xffdc88,side*.22,2.51,0,g);}box(.17,.035,.035,0x415e72,0,1.62,-.32,g);cyl(.1,.08,0xffdc88,0,1.1,-.37,g).rotation.x=Math.PI/2;box(.34,.4,.17,0x6e82a4,0,1.14,.39,g);}
 return{g,legs,arms};}
function character(boss:boolean,index:number){if(!boss&&enemyKind(index)!=='toy')return creature(enemyKind(index),index);const g=new T.Group(),color=boss?LEVELS[level].accent:[0xffa3b3,0x72d8c4,0xaca0e5,0xffca83][index%4];box(.7,.7,.43,color,0,1.05,0,g);box(.5,.12,.5,0x47627d,0,.66,0,g);cyl(.30,.48,0xffe2ba,0,1.75,0,g);cyl(.12,.08,0xffe2ba,0,2.03,0,g);const hair=cyl(.32,.14,color,0,1.98,0,g);for(const s of [-1,1]){ball(.07,0x2d4154,s*.11,1.77,-.29,g);ball(.022,0xffffff,s*.11-.015,1.79,-.35,g);box(.15,.05,.025,0xfab0b0,s*.18,1.64,-.26,g);}const smile=new T.Mesh(new T.TorusGeometry(.075,.01,5,16,Math.PI),mat(0x815c64));smile.position.set(0,1.64,-.31);smile.rotation.z=Math.PI;g.add(smile);const legs:T.Group[]=[],arms:T.Group[]=[];for(const s of [-1,1]){const leg=new T.Group();leg.position.set(s*.18,.66,0);box(.24,.46,.26,0x48647e,0,-.22,0,leg);box(.28,.16,.4,0xfffaf0,0,-.48,-.08,leg);g.add(leg);legs.push(leg);const arm=new T.Group();arm.position.set(s*.46,1.35,0);box(.22,.42,.26,color,0,-.2,0,arm);const hand=new T.Mesh(new T.TorusGeometry(.105,.045,6,12,Math.PI*1.5),mat(0xffe2ba));hand.position.set(0,-.46,-.02);arm.add(hand);g.add(arm);arms.push(arm);}cyl(.07,.45,0x577388,.43,.87,-.32,g).rotation.x=Math.PI/2;box(.32,.4,.16,0xffdb8d,0,1.1,.31,g);
 if(boss&&level===2){const cap=ball(.65,0xf393a2,0,2.15,0,g);cap.scale.y=.45;for(const x of [-.3,0,.3])ball(.09,0xfff2d1,x,2.39,-.1,g);}
 if(boss&&level===5){cyl(.4,.1,0x597993,0,2.13,0,g);cyl(.27,.48,0x597993,0,2.38,0,g);cyl(.28,.1,0xffcd73,0,2.26,0,g);}
 if(boss){g.scale.setScalar(2.4);for(let i=0;i<5;i++){const crown=mesh(new T.ConeGeometry(.1,.4,5),0xffda75,(i-2)*.13,2.23,0,g);}const belt=box(.8,.1,.48,0xffd76e,0,1.0,0,g);}
 return{g,legs,arms};}
function spawnWave(){wave++;const count=3+Math.floor(level*.7)+(wave===2?2:0);enemies=[];for(let i=0;i<count;i++)spawnEnemy(false,i);if(wave===2&&LEVELS[level].boss)spawnEnemy(true,count);toast(wave===1?'WAVE 1 · CLEAR THE ISLAND':LEVELS[level].boss?'BOSS WAVE · '+LEVELS[level].boss:'FINAL WAVE');}
function spawnEnemy(boss:boolean,index:number){const {g,legs,arms}=character(boss,index),rand=rng(889+level*91+wave*17+index*7);let x=0,z=0;for(let i=0;i<100;i++){const a=rand()*Math.PI*2,r=7+rand()*(LEVELS[level].half-11);x=Math.cos(a)*r;z=Math.sin(a)*r;if(!blocked(x,z))break;}if(blocked(x,z)){x=0;z=-6;}g.position.set(x,0,z);world.add(g);const kind:EnemyKind=boss?"toy":enemyKind(index),max=boss?360+level*62:Math.round((65+level*12)*(kind==="dinosaur"?1.2:kind==="ninja"?.85:1));enemies.push({kind,id:index,obj:g,x,z,hp:max,max,boss,phase:rand()*6,cool:1.4+rand(),wind:0,legs,arms,radius:boss?1.5:.65});}
function toast(text:string){$('toast').textContent=text;$('toast').classList.add('visible');setTimeout(()=>$('toast').classList.remove('visible'),2300);}
function equip(n:number){reload=0;weapon=n;disposeChildren(gun);const w=weapons[n];if(n===4){box(.16,.18,.9,0x8d7364,0,0,0,gun);box(.85,.09,.15,w.color,0,.02,-.35,gun);const string=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(-.4,.04,-.35),new T.Vector3(0,.04,.05),new T.Vector3(.4,.04,-.35)]),new T.LineBasicMaterial({color:0xfff4d5}));gun.add(string);box(.035,.035,.65,0xe1f2fa,0,.13,-.35,gun);}else if(n===5){box(.11,.8,.045,w.color,0,.3,-.15,gun);box(.42,.07,.14,0xffd77e,0,-.13,-.15,gun);box(.09,.28,.09,0x6b7d9b,0,-.3,-.15,gun);}else if(n===6){for(let i=0;i<4;i++){const blade=box(.38,.07,.09,w.color,0,0,0,gun);blade.rotation.y=i*Math.PI/4;}}else if(n===3){ball(.2,w.color,0,0,0,gun);cyl(.05,.09,0xffdc7b,0,.22,0,gun);}else{box(.25,.25,.64,w.color,0,0,0,gun);box(.28,.08,.4,0xe1eff0,0,.17,0,gun);box(.09,.23,.18,0x526781,0,-.2,.1,gun);const barrel=cyl(n===1?.09:.055,.5,0x59718a,0,.02,-.48,gun);barrel.rotation.x=Math.PI/2;if(n===2)ball(.17,0xffa4c9,0,.3,.06,gun);}box(.2,.14,.25,0xffddba,-.09,-.17,.28,gun);gun.position.set(.38,-.34,-.72);hud();}
function disposeChildren(o:T.Object3D){for(const child of [...o.children])dispose(child);}
function playerSpawnClear(){return !covers.some(c=>Math.abs(c.x)<c.w/2+1.2&&c.z+c.d/2>-2&&c.z-c.d/2<6);}
function start(n:number){building=false;buildCount=0;ghost.visible=false;level=Math.max(0,Math.min(9,n));wave=0;hp=100;score=0;kills=0;ammo=weapons.map(w=>w.cap);bolts.forEach(b=>dispose(b.obj));bolts=[];reload=fireCd=0;vy=0;jumps=0;clock=0;yaw=pitch=0;keys.clear();moveX=moveY=0;movePointer=lookPointer=null;mouse=false;shots.forEach(s=>dispose(s.obj));shots=[];grenades.forEach(g=>dispose(g.obj));grenades=[];fx.forEach(f=>dispose(f.obj));fx=[];pickups=[];portal=null;buildMap(level);pos.set(0,1.7,4);equip(0);spawnWave();mode='play';$('overlay').classList.add('hidden');$('hud').classList.remove('hidden');sound('start');capture();playLevelMusic(true);hud();}
function capture(){lock=true;renderer.domElement.focus();if(matchMedia('(pointer:coarse)').matches){sound('ready');return;}try{const p=renderer.domElement.requestPointerLock();p?.catch(()=>{});}catch{}sound('ready');}
function pause(){if(mode!=='play')return;mode='pause';pauseLevelMusic();lock=false;mouse=false;moveX=moveY=0;movePointer=lookPointer=null;$('joystick-stick').style.transform='translate(0,0)';keys.clear();document.exitPointerLock?.();showOverlay('PAUSED','Your island is waiting.','RESUME',()=>{mode='play';$('overlay').classList.add('hidden');capture();playLevelMusic();},true);}
function showOverlay(title:string,text:string,button:string,action:()=>void,secondary=false){$('overlay').classList.remove('hidden');$('panel-title').textContent=title;$('panel-copy').textContent=text;$('primary').textContent=button;$('primary').onclick=action;$('level-grid').classList.add('hidden');$('menu-button').classList.toggle('hidden',!secondary);}
function menu(){mode='menu';pauseLevelMusic();lock=false;document.exitPointerLock?.();keys.clear();moveX=moveY=0;movePointer=lookPointer=null;mouse=false;$('hud').classList.add('hidden');showOverlay('POPSHOT','Ten colorful worlds. Eight toy weapons. Three boss battles. One big adventure.','CONTINUE ADVENTURE',()=>start(Math.min(9,unlocked-1)));$('level-grid').classList.remove('hidden');$('level-grid').innerHTML=LEVELS.map((l,i)=>`<button ${i>=unlocked?'disabled':''} data-level="${i}"><b>${String(i+1).padStart(2,'0')}</b><span>${l.name}</span><small>${l.boss?'BOSS WORLD':i>=unlocked?'LOCKED':'2 WAVES'}</small></button>`).join('');$('level-grid').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>start(Number(b.dataset.level))));}
function damageEnemy(e:Enemy,amount:number){if(e.hp<=0)return;e.hp=Math.max(0,e.hp-amount);particles(e.obj.position.clone().add(new T.Vector3(0,e.boss?3:1.2,0)),weapons[weapon].color,7);sound('hit');if(!e.hp){score+=e.boss?500:100;kills++;confetti(e.obj.position.clone().add(new T.Vector3(0,1.4,0)));dispose(e.obj);if(Math.random()<.35||e.boss){const p=ball(.28,0x74efb8,e.x,.6,e.z);pickups.push(p);}sound('pop');}}
function hurt(amount:number){if(mode!=='play')return;hp=Math.max(0,hp-amount);$('damage').style.opacity='.5';setTimeout(()=>$('damage').style.opacity='0',180);sound('hurt');if(!hp){mode='dead';pauseLevelMusic();lock=false;mouse=false;document.exitPointerLock?.();showOverlay('QUICK PIT STOP',`Level ${level+1}: ${LEVELS[level].name}. Retry with full health and a fresh loadout.`,'RETRY LEVEL',()=>start(level),true);}}
function fire(){if(building){placeBuild();return;}if(mode!=='play'||!lock||fireCd>0||reload>0)return;const w=weapons[weapon];if(!ammo[weapon]){doReload();return;}if(Number.isFinite(ammo[weapon]))ammo[weapon]--;fireCd=w.rate;sound(['rifle','shotgun','splat','grenade','rifle','shotgun','splat','rifle'][weapon]);const dir=new T.Vector3(-Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch));gun.rotation.x=-.12;
 if(weapon===5){gun.rotation.z=-.8;for(const e of enemies){const center=new T.Vector3(e.x,e.boss?2.4:1.15,e.z),delta=center.clone().sub(pos);if(e.hp>0&&delta.length()<3.3&&delta.normalize().dot(dir)>.45&&clear(pos,center))damageEnemy(e,w.damage);}const arc=new T.Mesh(new T.TorusGeometry(1.2,.035,6,24,Math.PI*.8),new T.MeshBasicMaterial({color:w.color,transparent:true,opacity:.7}));arc.position.copy(pos).addScaledVector(dir,1.4);arc.quaternion.copy(camera.quaternion);scene.add(arc);fx.push({obj:arc,life:.13,total:.13,v:new T.Vector3(),growth:0});hud();return;}
 if(weapon===4||weapon===6){const obj=new T.Group();if(weapon===4){const shaft=cyl(.035,.65,0xffe7bb,0,0,0,obj);shaft.rotation.x=Math.PI/2;const tip=mesh(new T.ConeGeometry(.09,.2,4),0xd6f2ff,0,0,-.4,obj);tip.rotation.x=-Math.PI/2;}else for(let i=0;i<4;i++){const blade=box(.42,.055,.08,w.color,0,0,0,obj);blade.rotation.y=i*Math.PI/4;}obj.position.copy(pos);obj.quaternion.copy(camera.quaternion);scene.add(obj);bolts.push({obj,v:dir.multiplyScalar(weapon===4?30:21),life:3,damage:w.damage,spin:weapon===6});hud();return;}
 if(weapon===3){const g=new T.Group();ball(.18,w.color,0,0,0,g);box(.36,.05,.09,0xffe17b,0,0,0,g);g.position.copy(pos);scene.add(g);grenades.push({obj:g,v:dir.multiplyScalar(12).add(new T.Vector3(0,5,0)),fuse:1.45});return;}
 const caster=new T.Raycaster(pos,dir,0,weapon===1?20:65);world.updateMatrixWorld(true);const obstacles=world.children.filter(o=>o instanceof T.Mesh&&!(o instanceof T.Sprite));const impact=caster.intersectObjects(obstacles,false)[0];let distance=impact?.distance??65,target:Enemy|null=null;for(const e of enemies){if(e.hp<=0)continue;const center=new T.Vector3(e.x,e.boss?2.4:1.15,e.z),delta=center.clone().sub(pos),along=delta.dot(dir),perp=delta.addScaledVector(dir,-along).length();if(along>0&&along<distance&&along<(weapon===1?20:65)&&perp<e.radius+(weapon===1?.55:0)&&clear(pos,center)){target=e;distance=along;}}
 const end=pos.clone().addScaledVector(dir,distance);if(target)damageEnemy(target,w.damage);const col=weapon===2?[0xf879ba,0x62eccf,0xffd564,0xa28cef][ammo[weapon]%4]:0xffe5a3;const line=new T.Line(new T.BufferGeometry().setFromPoints([pos.clone().add(new T.Vector3(.2,-.2,0)),end]),new T.LineBasicMaterial({color:col}));scene.add(line);fx.push({obj:line,life:.08,total:.08,v:new T.Vector3(),growth:0});if(weapon===2)particles(end,col,12,5);hud();}
function buildCandidate(){return{x:Math.round((pos.x-Math.sin(yaw)*5.5)/4)*4,z:Math.round((pos.z-Math.cos(yaw)*5.5)/4)*4};}
function buildAllowed(x:number,z:number){return Math.abs(x)<LEVELS[level].half-3&&Math.abs(z)<LEVELS[level].half-3&&buildCount<24&&!covers.some(c=>Math.abs(c.x-x)<c.w/2+1.9&&Math.abs(c.z-z)<c.d/2+1.9)&&Math.hypot(x-pos.x,z-pos.z)>2.3&&!enemies.some(e=>e.hp>0&&Math.hypot(e.x-x,e.z-z)<2.5);}
function toggleBuild(){building=!building;mouse=false;ghost.visible=building;toast(building?'BUILD · 1 WALL · 2 RAMP · 3 FLOOR · 4 ROOF · R ROTATE':'BACK TO BLASTERS');}
let blueprintStyle="";function previewBuild(){ghost.visible=building&&mode==='play';if(!ghost.visible)return;const p=buildCandidate(),ok=buildAllowed(p.x,p.z);const style=buildType+":"+ok;if(style!==blueprintStyle){blueprintStyle=style;disposeChildren(ghost);const m=new T.Mesh(new T.BoxGeometry(4,buildType===2?.18:buildType===3?1.6:2.8,buildType===0?.28:4),new T.MeshBasicMaterial({color:ok?0x93ffe0:0xff99ac,transparent:true,opacity:.25,depthWrite:false}));m.position.y=buildType===2?.1:buildType===3?.8:1.4;ghost.add(m);}ghost.position.set(p.x,0,p.z);ghost.rotation.y=buildRotation*Math.PI/2;$('build-hint').textContent=(ok?'CLICK TO PLACE':'MOVE TO A CLEAR SPACE')+' · '+buildCount+'/24';}
function placeBuild(){if(mode!=='play'||!lock||fireCd>0)return;fireCd=.3;const p=buildCandidate();if(!buildAllowed(p.x,p.z)){toast('Find a clear square · 24 builds per world');return;}const color=LEVELS[level].accent,rot=buildRotation%2;const add=(x:number,z:number,w:number,d:number,h:number)=>{covers.push({x,z,w,d,h});box(w,h,d,color,x,h/2,z);};if(buildType===0)add(p.x,p.z,rot?.3:4,rot?4:.3,2.8);if(buildType===2)add(p.x,p.z,4,4,.18);if(buildType===1)for(let i=0;i<16;i++){const shift=-2+(i+.5)*.25;add(p.x+(rot?shift:0),p.z+(rot?0:shift),rot?.25:4,rot?4:.25,(i+1)*.175);}if(buildType===3)for(let i=0;i<8;i++)add(p.x,p.z,4-i*.45,4-i*.45,(i+1)*.2);buildCount++;sound('land');particles(new T.Vector3(p.x,1,p.z),color,14);mouse=false;}
function doReload(){if(reload||ammo[weapon]===weapons[weapon].cap||mode!=='play')return;reload=weapon===3?2.2:1.3;sound('reload');}
function win(){mode='clear';pauseLevelMusic();lock=false;mouse=false;document.exitPointerLock?.();unlocked=Math.max(unlocked,Math.min(10,level+2));save.unlocked=unlocked;save.best=save.best||{};save.best[level]=Math.max(save.best[level]||0,score);if(level===9)save.completed=true;saveProgress();sound('finish');confetti(pos.clone());showOverlay(level===9?'CAMPAIGN COMPLETE!':'WORLD COMPLETE!',`${LEVELS[level].name} cleared · ${score} points · ${kills} rivals popped. ${level===9?'You defeated the Prism Titan!':'The next island is bigger and tougher.'}`,level===9?'BACK TO WORLDS':'NEXT WORLD',()=>level===9?menu():start(level+1),true);}
function enemyShot(e:Enemy,angle=0){const at=new T.Vector3(e.x,e.boss?2.6:1.35,e.z),dir=pos.clone().add(new T.Vector3(0,-.35,0)).sub(at).normalize();dir.applyAxisAngle(new T.Vector3(0,1,0),angle);const p=ball(e.boss?.19:.12,e.boss?0xffac8b:e.kind==='dinosaur'?0x8beb77:e.kind==='ninja'?0xffd581:0x9b9aff,at.x,at.y,at.z,scene);shots.push({obj:p,v:dir.multiplyScalar((7+level*.55)*(e.kind==='ninja'?1.2:e.kind==='dinosaur'?.85:1)),life:7,damage:e.boss?12+level:(e.kind==='dinosaur'?9:5)+Math.floor(level*.75)});}
function tick(dt:number){clock+=dt;fireCd=Math.max(0,fireCd-dt);if(reload){reload=Math.max(0,reload-dt);if(!reload){ammo[weapon]=weapons[weapon].cap;sound('ready');}}if(mouse)fire();let fw=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0),side=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0);fw+=-moveY;side+=moveX;const len=Math.max(1,Math.hypot(fw,side)),speed=keys.has('ShiftLeft')?7.6:5.5;
 const grounded=jumps===0&&Math.abs(pos.y-(floor(pos.x,pos.z)+1.7))<.08;
 const moveAxis=(dx:number,dz:number)=>{const nx=pos.x+dx,nz=pos.z+dz,feet=pos.y-1.7,top=floor(nx,nz);if(!blocked(nx,nz,feet)||(grounded&&top-feet<=.23&&!blocked(nx,nz,top))){pos.x=nx;pos.z=nz;if(grounded&&top>feet)pos.y=top+1.7;}};
 moveAxis((-Math.sin(yaw)*fw+Math.cos(yaw)*side)/len*speed*dt,0);moveAxis(0,(-Math.cos(yaw)*fw-Math.sin(yaw)*side)/len*speed*dt);
 vy-=22*dt;const previous=pos.y;pos.y+=vy*dt;const ground=floor(pos.x,pos.z)+1.7;if(pos.y<=ground&&previous>=ground-.3&&vy<=0){pos.y=ground;vy=0;jumps=0;}if(pos.y<1.7){pos.y=1.7;vy=0;jumps=0;}
 camera.position.copy(pos);camera.rotation.set(pitch,yaw,0);gun.rotation.x*=Math.exp(-12*dt);gun.rotation.z*=Math.exp(-10*dt);gun.position.y=-.34;
 for(const e of enemies){if(e.hp<=0)continue;const dx=pos.x-e.x,dz=pos.z-e.z,d=Math.max(.01,Math.hypot(dx,dz)),speed=e.boss?1.65+level*.08:(1.5+level*.12)*(e.kind==='ninja'?1.45:e.kind==='dinosaur'?.85:1);const origin=new T.Vector3(e.x,e.boss?2.6:1.35,e.z),visible=clear(origin,pos);const movement=!visible||d>(e.kind==='dinosaur'?6:9)?1:d<4?-1:0;let moved=0;
 if(movement){const facing=Math.atan2(dx,dz)+(movement<0?Math.PI:0)+(e.kind==='ninja'&&visible?Math.sin(clock*2+e.id)*.65:0);let best=-Infinity,bx=e.x,bz=e.z;for(const turn of [0,.55,-.55,1.1,-1.1,1.65,-1.65]){const nx=e.x+Math.sin(facing+turn)*speed*dt,nz=e.z+Math.cos(facing+turn)*speed*dt;if(blocked(nx,nz)||enemies.some(other=>other!==e&&other.hp>0&&Math.hypot(nx-other.x,nz-other.z)<.9))continue;const progress=(d-Math.hypot(pos.x-nx,pos.z-nz))*movement;const rating=progress-Math.abs(turn)*.005;if(rating>best){best=rating;bx=nx;bz=nz;}}moved=Math.hypot(bx-e.x,bz-e.z);e.x=bx;e.z=bz;}
 e.phase+=moved*6;e.obj.position.set(e.x,0,e.z);e.obj.rotation.y=Math.atan2(-dx,-dz);const stride=moved>.0001?Math.round(Math.sin(e.phase)*3)/3*.48:0;e.legs.forEach((g,i)=>g.rotation.x=stride*(i?-1:1));e.arms.forEach((g,i)=>g.rotation.x=e.wind>0?-.85:-stride*(i?-1:1));e.cool-=dt;if(e.cool<=0&&e.wind===0&&d<LEVELS[level].half*1.5&&visible){e.wind=e.boss?.7:.35;e.obj.scale.multiplyScalar(1.06);}if(e.wind>0){e.wind-=dt;if(e.wind<=0){e.wind=0;e.obj.scale.setScalar(e.boss?2.4:1);e.cool=Math.max(.75,2.5-level*.14)*(e.kind==='dinosaur'?1.3:e.kind==='ninja'?.85:1);if(e.boss){for(const a of level===2?[-.2,0,.2]:level===5?[-.4,-.2,0,.2,.4]:[-.6,-.4,-.2,0,.2,.4,.6])enemyShot(e,a);if(level===9&&e.hp<e.max*.5&&enemies.filter(x=>x.hp>0&&!x.boss).length<2)spawnEnemy(false,20+Math.floor(clock));}else if(e.kind==='alien'){enemyShot(e,-.09);enemyShot(e,.09);}else enemyShot(e);}}}
 for(let i=bolts.length-1;i>=0;i--){const b=bolts[i],from=b.obj.position.clone(),travel=b.v.length()*dt,direction=b.v.clone().normalize();let hit:Enemy|null=null,nearest=travel;const ray=new T.Raycaster(from,direction,0,travel);world.updateMatrixWorld(true);const wall=ray.intersectObjects(world.children.filter(o=>o instanceof T.Mesh),false)[0];if(wall)nearest=wall.distance;for(const e of enemies){if(e.hp<=0)continue;const center=new T.Vector3(e.x,e.boss?2.4:1.15,e.z),offset=center.clone().sub(from),along=offset.dot(direction);if(along>=-e.radius&&along<=nearest&&offset.addScaledVector(direction,-along).length()<e.radius+.12&&clear(from,center)){hit=e;nearest=Math.max(0,along);}}b.obj.position.addScaledVector(direction,nearest);if(b.spin)b.obj.rotation.z+=dt*22;b.life-=dt;if(hit){damageEnemy(hit,b.damage);b.life=0;}else if(wall)b.life=0;if(b.life<=0){particles(b.obj.position.clone(),b.spin?0xe2a5fa:0xffca78,4,2);dispose(b.obj);bolts.splice(i,1);}}
 for(let i=shots.length-1;i>=0;i--){const s=shots[i];s.obj.position.addScaledVector(s.v,dt);s.life-=dt;if(s.obj.position.distanceTo(pos.clone().add(new T.Vector3(0,-.4,0)))<.5){hurt(s.damage);s.life=0;}if(covers.some(c=>Math.abs(s.obj.position.x-c.x)<c.w/2&&Math.abs(s.obj.position.z-c.z)<c.d/2&&s.obj.position.y<c.h))s.life=0;if(s.life<=0){dispose(s.obj);shots.splice(i,1);}}
 for(let i=grenades.length-1;i>=0;i--){const g=grenades[i],p=g.obj.position,nx=p.x+g.v.x*dt,nz=p.z+g.v.z*dt;if(blocked(nx,p.z,p.y))g.v.x*=-.55;else p.x=nx;if(blocked(p.x,nz,p.y))g.v.z*=-.55;else p.z=nz;g.v.y-=13*dt;p.y+=g.v.y*dt;const ground=floor(p.x,p.z)+.2;if(p.y<ground){p.y=ground;g.v.y=Math.abs(g.v.y)*.4;g.v.x*=.75;g.v.z*=.75;}g.obj.rotation.y+=dt*8;g.fuse-=dt;if(g.fuse<=0){confetti(p.clone());sound('explosion');for(const e of enemies){const at=new T.Vector3(e.x,e.boss?2.4:1.1,e.z),d=at.distanceTo(p);if(e.hp>0&&d<5&&clear(p.clone().add(new T.Vector3(0,.3,0)),at))damageEnemy(e,Math.round(85-d*10));}if(p.distanceTo(pos)<4)hurt(24);dispose(g.obj);grenades.splice(i,1);}}
 for(let i=pickups.length-1;i>=0;i--){const p=pickups[i];p.rotation.y+=dt*2;p.position.y=.6+Math.sin(clock*3)*.1;if(p.position.distanceTo(pos)<2){hp=Math.min(100,hp+25);sound('ready');dispose(p);pickups.splice(i,1);toast('+25 HEALTH');}}
 if(mode==='play'&&enemies.every(e=>e.hp<=0)){if(wave<2){shots.forEach(s=>dispose(s.obj));shots=[];spawnWave();hp=Math.min(100,hp+20);}else win();}}
function hud(){$('level-name').textContent=LEVELS[level].name;$('level-number').textContent=`WORLD ${level+1} / 10 · WAVE ${wave} / 2`;$('health').textContent=String(hp);$('health-fill').style.width=hp+'%';$('ammo').textContent=reload?'…':Number.isFinite(ammo[weapon])?String(ammo[weapon]):'∞';$('weapon-name').textContent=weapons[weapon].name;$('score').textContent=String(score);$('remaining').textContent=enemies.filter(e=>e.hp>0).length+' RIVALS LEFT';const boss=enemies.find(e=>e.boss&&e.hp>0);$('boss').classList.toggle('hidden',!boss);if(boss){$('boss-name').textContent=LEVELS[level].boss;$('boss-fill').style.width=(boss.hp/boss.max*100)+'%';}$('loadout').querySelectorAll('button').forEach((b,i)=>{b.classList.toggle('hidden',building&&i>=4);b.classList.toggle('active',i===(building?buildType:weapon));const text='<kbd>'+(i+1)+'</kbd>'+(building?['WALL','RAMP','FLOOR','ROOF'][i]:weapons[i].name);if(b.innerHTML!==text)b.innerHTML=text;});$('build-hint').classList.toggle('hidden',!building);}
$('loadout').innerHTML=weapons.map((w,i)=>`<button><kbd>${i+1}</kbd>${w.name}</button>`).join('');$('loadout').querySelectorAll('button').forEach((b,i)=>b.onclick=()=>{if(building)buildType=i;else equip(i);});$('menu-button').onclick=menu;$('sound').onclick=()=>{muted=!muted;levelMusic.muted=muted;if(muted)pauseLevelMusic();else playLevelMusic();$('sound').textContent=muted?'SOUND OFF':'SOUND ON';if(audio){audio.muted=muted;audio.update();}};$('back').onclick=()=>{if(parent!==window)parent.postMessage({type:'popshot-close'},location.origin);else location.href='../../index.html';};
addEventListener('keydown',e=>{if(e.code==='Escape'){pause();return;}if(mode!=='play')return;keys.add(e.code);if(e.code==='Space'){e.preventDefault();if(!e.repeat&&jumps<2){vy=jumps?8.7:9.5;jumps++;sound(jumps===2?'double':'jump');}}if(e.code==='KeyB'&&!e.repeat)toggleBuild();if(e.code==='KeyR'){if(building)buildRotation++;else doReload();}if(/^Digit[1-8]$/.test(e.code)){const n=Number(e.code.slice(-1))-1;if(building){if(n<4)buildType=n;}else equip(n);}if(e.code==='KeyQ'&&!building)equip((weapon+1)%weapons.length);});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',pause);
renderer.domElement.tabIndex=0;renderer.domElement.addEventListener('pointerdown',e=>{if(mode!=='play')return;if(!lock)capture();if(e.pointerType==='touch'){if(lookPointer!==null)return;e.preventDefault();lookPointer=e.pointerId;renderer.domElement.setPointerCapture(e.pointerId);}drag=true;lastX=e.clientX;lastY=e.clientY;if(e.pointerType==='mouse'&&e.button===0)mouse=true;});
addEventListener('pointerup',e=>{if(e.pointerType==='mouse'){mouse=false;drag=false;}if(e.pointerId===lookPointer){lookPointer=null;drag=false;}});addEventListener('pointercancel',e=>{if(e.pointerId===lookPointer){lookPointer=null;drag=false;}});
addEventListener('pointermove',e=>{if(mode!=='play'||!lock)return;if(e.pointerType==='touch'&&e.pointerId!==lookPointer)return;const captured=e.pointerType==='mouse'&&document.pointerLockElement===renderer.domElement;const dx=captured?e.movementX:drag?e.clientX-lastX:0,dy=captured?e.movementY:drag?e.clientY-lastY:0;yaw-=dx*(e.pointerType==='touch'?.005:.0025);pitch=Math.max(-1.3,Math.min(1.3,pitch-dy*(e.pointerType==='touch'?.005:.0025)));lastX=e.clientX;lastY=e.clientY;});
document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&mode==='play'&&lock)pause();});
for(const b of document.querySelectorAll<HTMLButtonElement>('[data-key]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key!);};b.onpointerup=()=>keys.delete(b.dataset.key!);b.onpointercancel=()=>keys.delete(b.dataset.key!);} $('touch-fire').onpointerdown=e=>{e.preventDefault();($('touch-fire') as HTMLElement).setPointerCapture(e.pointerId);mouse=true;};$('touch-fire').onpointerup=()=>mouse=false;$('touch-fire').onpointercancel=()=>mouse=false;$('touch-jump').onclick=()=>{if(mode==='play'&&jumps<2){vy=jumps?8.7:9.5;jumps++;sound('jump');}};$('pause').onclick=pause;$('build-button').onclick=toggleBuild;
addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();});let last=performance.now();function loop(now:number){const dt=Math.min(.1,Math.max(0,(now-last)/1000));last=now;if(mode==='play'&&lock){let remaining=dt;while(remaining>0&&mode==='play'){const step=Math.min(1/120,remaining);tick(step);remaining-=step;}}else if(mode==='menu'){camera.position.set(Math.sin(now*.00008)*23,12,Math.cos(now*.00008)*23);camera.lookAt(0,1,0);gun.visible=false;}else gun.visible=mode!=='menu';if(mode==='play')gun.visible=!building;for(let i=fx.length-1;i>=0;i--){const f=fx[i];f.life-=dt;if(f.growth)f.obj.scale.addScalar(dt*f.growth);else{f.obj.position.addScaledVector(f.v,dt);f.v.y-=8*dt;}if(f.life<=0){dispose(f.obj);fx.splice(i,1);}}audio?.tick(mode==='play'&&lock);ghost.visible=building&&mode==='play';if(mode==='play'){previewBuild();hud();}renderer.render(scene,camera);requestAnimationFrame(loop);}buildMap(0);equip(0);menu();requestAnimationFrame(loop);
// Read-only test hook: campaign state is inspectable without exposing control to players.
(window as any).__popshotCampaign={snapshot:()=>({level:level+1,wave,hp,score,mode,unlocked,enemies:enemies.filter(e=>e.hp>0).length,mapSize:LEVELS[level].half*2}),levels:LEVELS};

$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('Fullscreen unavailable here · open the game directly or use your browser fullscreen');}};document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'EXIT FULLSCREEN':'FULLSCREEN';});

const joystick=$('joystick'),stick=$('joystick-stick');function moveStick(e:PointerEvent){const r=joystick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,limit=r.width*.32,len=Math.hypot(dx,dy),scale=len>limit?limit/len:1;moveX=dx*scale/limit;moveY=dy*scale/limit;stick.style.transform=`translate(${dx*scale}px,${dy*scale}px)`;}
joystick.onpointerdown=e=>{if(mode!=='play'||movePointer!==null)return;e.preventDefault();movePointer=e.pointerId;joystick.setPointerCapture(e.pointerId);moveStick(e);};joystick.onpointermove=e=>{if(e.pointerId===movePointer){e.preventDefault();moveStick(e);}};const resetStick=(e:PointerEvent)=>{if(e.pointerId===movePointer){movePointer=null;moveX=moveY=0;stick.style.transform='translate(0,0)';}};joystick.onpointerup=resetStick;joystick.onpointercancel=resetStick;joystick.onlostpointercapture=resetStick;
$('touch-reload').onclick=doReload;$('new-tab').onclick=()=>window.open(location.href,'_blank','noopener');

addEventListener('pagehide',pauseLevelMusic);
